### ISSUE TITLE
Major use case: contact a bus company and add a new trip

### ISSUE THREAD

**Issue by 12foo** [SandersForPresident/BusRSVP#18]
## Contacting a bus company

App displays a friendly help page that lays out how to contact a bus company and arrange to charter a bus. Common pitfalls, what to ask, and other helpful information is displayed together with a list of what the user (trip host) should know by the end of the conversation:

* available seating in the bus
* price
* possible departure dates and places

## Adding a new bus trip

App displays a screen where a user can add a bus trip and take ownership of it. Every trip is linked to an event, and has pricing information, seat availability, and a departure date and location. The user should be verified in some way, and contact information is required (so people RSVPing seats can contact the host about problems wrt/ the upcoming trip).

**Comment by kris-luminar** [comment]
> contact a bus company and arrange to charter a bus.

Oh, I imagined this app interfacing with a bus trip that had already been planned instead of facilitating actual chartering of a bus.

**Comment by 12foo** [comment]
I'm not clear myself on how this is supposed to go down, but clearly the bus trips have to come from *somewhere*. So if hosts can't self-register to create new trips, who is putting them in? If this is solved somewhere else (like there's a campaign database of bus trips or something), do feel free to delete the issue.

**Comment by maclover7** [comment]
Not sure we're going to be able to do this -- I highly doubt that bus companies have pluggable APIs. We could have a "getting started" guide, but this information would probably have to be provided by the campaign (I'm not sure how bus trip reservations work). Closing this for now -- feel free to reopen if you feel necessary.
