### ISSUE TITLE
Integrate Berniestrap

### ISSUE THREAD

**Issue by maclover7** [SandersForPresident/BusRSVP#2]
Use Berniestrap styles for the website

**Comment by industriousthought** [comment]
Hey, is this the Bootstrap fork in SandersForPresident?

**Comment by ajwhite** [comment]
@industriousthought you can find that here :point_down: 
https://github.com/SandersForPresident/bootstrap

**Comment by industriousthought** [comment]
Cool, thanks, that was what I was thinking, but wasn't sure.
