### ISSUE TITLE
Getting started?

### ISSUE THREAD

**Issue by randome** [SandersForPresident/BusRSVP#7]
Hi,

Can we get updated readme or something similar about the app functionality so people can start working towards something? :smile:

**Comment by maclover7** [comment]
Sure thing. Pretty much just take a look at the open issues, and submit a PR for any of them (make sure to include tests if necessary), and then tag me for code review. Send me a message on Slack if you have any questions :)

**Comment by maclover7** [comment]
Added a CONTRIBUTING.md file via #9
